project:
  type: website

website:

  page-footer: 
    left: "Smile, breathe and go slowly. - Thích Nhất Hạnh" 
    right: 
      - icon: github
        href: https://github.com/hoainam-le
      - icon: twitter
        href: https://x.com/NamLeHoai97
      - icon: facebook
        href: https://www.facebook.com/namhltv/
  
  title: "Nam Hoai Le"
  google-analytics: "G-BHPEXB34GQ"
  navbar:
    style: "floating"
    main-container-width: "wide"
    # logo: images/namle.jpg
    left:
      - text: "About"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Academic Activities"
        href: academic.qmd
      - text: "CV"
        href: cv.qmd
      - text: "More"
        menu:
          - text: "Honors & Awards"
            href: honors.qmd
          - text: "Useful Links"
            href: useful_links.qmd
      # - text: "Blog"
      #   menu:
      #     - text: "Academic"
      #       href: posts/academic/index.qmd
      #     - text: "Life"
      #       href: posts/life/index.qmd
    # right:
    #   - icon: github
    #     href: https://github.com/hoainam-le
    #   - icon: twitter
    #     href: https://x.com/NamLeHoai97
    #   - icon: facebook
    #     href: https://www.facebook.com/namhltv/
    

format:
  html:
    page-layout: full
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right

  