project:
  type: website

website:
  title: "Hoai Nam Le"
  navbar:
    left:
      - text: "About"
        href: index.qmd
      - text: "Publications"
        href: publications.qmd
      - text: "Teaching"
        href: teaching.qmd
      - text: "Academic Activities"
        href: academic.qmd
      - text: "Honors & Awards"
        href: honors.qmd
      - text: "CV"
        href: 'cv.qmd'




format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true



