---
title: "Research"
---
<br>

## Publications and Preprints

1. **The exceptional set in Cassel's theorem on small cyclotomic integers**, with [Jitendra Bajpai](https://user.math.uni-kiel.de/~jitendra/){.collaborator-link target="_blank"}, [Srijan Das](https://sites.google.com/view/srijans-homepage/home){.collaborator-link target="_blank"}, [Kiran S. Kedlaya](https://kskedlaya.org/){.collaborator-link target="_blank"}, [Meghan Lee](https://meghanhlee.github.io/){.collaborator-link target="_blank"}, [Antoine Leudière](https://cspages.ucalgary.ca/~antoine.leudiere1/){.collaborator-link target="_blank"}, and [Jorge Mello](https://www.jorgemello.org/){.collaborator-link target="_blank"}, submitted.   
[arXiv](https://arxiv.org/pdf/2510.20435){.btn-pdf target="_blank"} [Code](https://github.com/castle-gray-rnt6/cassels){.btn-pdf target="_blank"} 

1. **Well-rounded twists of the ring of integrers of cyclic cubic fields**, with [Dat T. Tran](https://sites.google.com/view/ttdat1323/){.collaborator-link target="_blank"}, [Ha T. N. Tran](https://sites.google.com/site/hatrannguyenthanh){.collaborator-link target="_blank"}, and [Dave Karpuk](https://sites.google.com/view/davidkarpuk/){.collaborator-link target="_blank"}, submitted.    
[arXiv](http://arxiv.org/abs/2508.17123){.btn-pdf target="_blank"}  [Code](https://github.com/hoainam-le/wril_cubic_fields){.btn-pdf target="_blank"}  

1. **Well-Rounded ideal lattices of cyclic cubic and quartic fields**, with [Dat T. Tran](https://sites.google.com/view/ttdat1323/){.collaborator-link target="_blank"} and [Ha T. N. Tran](https://sites.google.com/site/hatrannguyenthanh){.collaborator-link target="_blank"}, _Communications in Mathematics_, October 18, 2023, Volume 31 (2023), Issue 2 (Special issue: Euclidean lattices: theory and applications).   
[arXiv](https://arxiv.org/abs/2303.16968){.btn-pdf target="_blank"} [Journal](https://cm.episciences.org/12425){.btn-pdf target="_blank"}

1. **Well-rounded twists of ideal lattices from imaginary quadratic fields**, with [Dat T. Tran](https://sites.google.com/view/ttdat1323/){.collaborator-link target="_blank"} and [Ha T. N. Tran](https://sites.google.com/site/hatrannguyenthanh){.collaborator-link target="_blank"}, _Journal of Algebra and Its Applications_, Vol. 21, No. 07, 2250133 (2022).  
[arXiv](https://arxiv.org/abs/2210.15049){.btn-pdf target="_blank"}
[Journal](https://www.worldscientific.com/doi/abs/10.1142/S021949882250133X){.btn-pdf target="_blank"}

---


## Projects

- **Well-Rounded ideal lattices of biquadratic and pure cubic fields**   
  <span style="color:gray">July 2025 – at present</span> with Dat T. Tran, Morgan Smith, and Ha T. N. Tran

- **The exceptional set in Cassels’s theorem on smallcyclotomic integers**   
  <span style="color:gray">June 2025 – October 2025</span> with Jitendra Bajpai, Srijan Das, Meghan Lee, Antoine Leudière, and Jorge Mello; under the supervision of Prof. Kiran S. Kedlaya.

- **Well-rounded Twists of Lattices in $\mathbb{R}^3$**  
  <span style="color:gray">July 2023 – June 2025</span> with Dave Karpuk, Dat T. Tran, and Ha T. N. Tran.

- **Well-rounded ideals of cubic and quartic fields**  
  <span style="color:gray">June 2021 – April 2023</span> with Dat T. Tran and Ha T. N. Tran.

- **On norm Euclidean tri-quadratic fields**  
  <span style="color:gray">May 2020 – February 2021</span> with Amy Feaver, Dat T. Tran, and Ha T. N. Tran.

- **Well-rounded twists of quadratic fields**  
  <span style="color:gray">January 2020 – June 2020</span> with Dat T. Tran and Ha T. N. Tran.
