---
title: "Algorithmic Number Theory (Spring 2024)"
format:
  html:
    css: ../../styles.css
bibliography: ../../references.bib
---

**Instructor:** Nam Hoai Le

**Lecture time and location:** Wednesdays, Linh Trung Campus, Thu Duc Ward (formerly Thu Duc District)

**Textbook:** Elementary Number Theory Its Applications - 6th eddition [@rosen2018elementary] by Kenneth H. Rosen

**Course Schedule**


::: {.course-table}
| Week | Section(s) | Topics (Morning) | Recommended Exercises | Lab (Afternoon) |
|------|--------|----------------------|----------------|---------------|
| **1** | 2.1<br> 2.2<br> 2.3<br> 3.1 <br>3.2* | Course intro<br>Algorithms & complexity<br>Integer representation<br>Primes | 2.1: 1–7<br> 2.2: 1–16<br> 2.3: 1–15 | — |
| **2** | 3.3<br> 3.4<br> 3.5<br> 3.6* | Euclid algorithm<br>Bézout lemma | 3.3: 1–32<br> 3.4: 1–10, 19, 20 | — |
| **3** | 3.7<br>4.1<br> 4.2<br>4.3<br>4.4–4.5*<br>5.1 | Diophantine equations<br>Congruences<br>Chinese Remainder Theorem<br>Linear congruence systems<br>Divisibility | 3.7: 1–10 <br>4.1: 5, 15, 30, 31, 36<br> 4.2: 1–2<br> 4.3: 4 | Lab 1 — Python Intro |
| **4** | 6.1<br>6.2<br>6.3<br>7.1<br>7.2 | Fermat & Wilson<br>Pseudoprimes & Carmichael numbers<br>Euler’s theorem<br>Arithmetic functions | 6.1: 12, 13, 15, 17<br> 6.2: 16,20<br> 6.3: 5–12<br> 7.1: 2,5,11,12 | Lab 2 — Loops & Linked Lists |
| **5** | 7.3<br>7.4<br>9.1 | Perfect numbers<br>Mersenne primes<br>Möbius function<br>Primitive roots | 9.1: 1–20 | Lab 3 — Data Structures |
| **6** | 11.1<br>11.2<br>11.3 | Quadratic residues<br>Legendre symbol<br>Jacobi symbol | 11.1: 4, 6, 8, 9, 10, 13, 20, 41<br> 11.2: 1 | Exercises + coding practice |
| **7** | — | Midterm review<br>90-min Midterm exam | — | Lab 4 — Object-Oriented Programming |
| **8** | 6.2<br>11.4 | Primality tests:<br>Deterministic — trivial method<br>Miller–Rabin<br>Euler pseudoprimes<br>Solovay–Strassen |Design and implement the corresponding primality-testing algorithms | Lab 5 — File I/O |
| **9** | 9.5<br>3.6<br>4.6<br>6.1<br>12.5 | Integer factorization:<br>Pollard's Rho<br>Pollard $p−1$<br>Continued fractions<br>Continued-fraction–based factorization<br>Number Field Sieve | Design and implement the corresponding integer factorization algorithms | Lab 6 — Modules |
| **10** | 8.1<br>8.2<br>8.3<br>8.4 <br>10.2| Caesar cipher<br>RSA<br>ElGamal | Implement encryption and decryption algorithms for RSA and ElGamal.| Exercises + practice |
| **11** | — | Discrete Logarithm Problem:<br>  Baby-Step Giant-Step<br>Pollard's Rho<br>Index calculus | Design and implement the corresponding discrete logarithm algorithms | Lab 7 — Packages |
| **12** | — | Review Midterm<br>Final exam prep | — | Lab 8 — Exceptions |
:::
\* Further Reading

